name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install zola
        run: |
          wget -q -O - \
          "https://github.com/getzola/zola/releases/download/v0.12.0/zola-v0.12.0-x86_64-unknown-linux-gnu.tar.gz" \
          | sudo tar xzf - -C /usr/local/bin
      - name: Build
        run: zola build

      - name: Push
        run: |
          cd public
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .
          git commit -m "Automatic deploy"
          git push --force "https://sophiajt:${{ secrets.TOKEN }}@github.com/sophiajt/sophiajt.github.io.git" master:master
